# Generated by Django 5.2.11 on 2026-02-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('white_player', models.CharField(max_length=100)),
                ('black_player', models.CharField(max_length=100)),
                ('pgn', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveExplanation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ply', models.IntegerField()),
                ('move_number', models.IntegerField()),
                ('color', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='chess.game')),
            ],
            options={
                'unique_together': {('game_id', 'ply')},
            },
        ),
    ]
